const Phenomenas = { // lots of em huh
    AF: "Ashfall(land)",
    AS: "Air Stagnation",
    BH: "Beach Hazard",
    BW: "Brisk Wind",
    BZ: "Blizzard",
    CF: "Coastal Flood",
    DF: "Debris Flow",
    DS: "Dust Storm",
    EC: "Extreme Cold",
    EH: "Excessive Heat",
    EW: "Extreme Wind",
    FA: "Areal Flood",
    FF: "Flash Flood",
    FG: "Dense Fog(land)",
    FL: "Flood",
    FR: "Frost",
    FW: "Fire Weather",
    FZ: "Freeze",
    GL: "Gale",
    HF: "Hurricane Force Wind",
    HT: "Heat",
    HU: "Hurricane",
    HW: "High Wind",
    HY: "Hydrologic",
    HZ: "Hard Freeze",
    IS: "Ice Storm",
    LE: "Lake Effect Snow",
    LO: "Low Water",
    LS: "Lakeshore Flood",
    LW: "Lake Wind",
    MA: "Marine",
    MF: "Dense Fog(marine)",
    MH: "Ashfall(marine)",
    MS: "Dense Smoke(marine)",
    RB: "Small Craft for Rough Bar",
    RP: "Rip Current Risk",
    SC: "Small Craft",
    SE: "Hazardous Seas",
    SI: "Small Craft for Winds",
    SM: "Dense Smoke(land)",
    SQ: "Snow Squall",
    SR: "Storm",
    SS: "Storm Surge",
    SU: "High Surf",
    SV: "Severe Thunderstorm",
    SW: "Small Craft for Hazardous Seas",
    TO: "Tornado",
    TR: "Tropical Storm",
    TS: "Tsunami",
    TY: "Typhoon",
    UP: "Heavy Freezing Spray",
    WC: "Wind Chill",
    WI: "Wind",
    WS: "Winter Storm",
    WW: "Winter Weather",
    ZF: "Freezing Fog",
    ZR: "Freezing Rain",
    ZY: "Freezing Spray",
}

module.exports=Phenomenas;